# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'User' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  # Pods for User

  target 'UserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
